security:

    providers:
        celebrityagent_user_provider:
            entity:
                class: CelebrityAgent\Entity\User
                property: email

    encoders:
        CelebrityAgent\Entity\User:
            algorithm: auto
            memory_cost: 16384
            time_cost: 3

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SYSTEM_ADMIN: ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login$
            anonymous: ~
        signup:
            pattern: ^/signup$
            anonymous: ~
        backoffice:
            host: ^backoffice\..+$
            provider: celebrityagent_user_provider
            remember_me:
                secret: '%env(resolve:APP_SECRET)%'
                lifetime: 31536000
                path: /
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                path: /logout
                target: /login
                invalidate_session: true
        site:
            anonymous: ~

    access_control:
        - { host: ^backoffice\..+$, path: ^/login.*$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: ^backoffice\..+$, path: ^/signup.*$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: ^backoffice\..+$, path: ^.*$, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
