admin:
    resource: '../../src/Controller/BackOffice/'
    type: annotation
    schemes: [https]
    host: 'backoffice.{domain}'
    requirements:
        domain: '%domain%'
    defaults:
        domain: '%domain%'

public:
    resource: '../../src/Controller/Site/'
    type: annotation
    schemes: [https]
    host: 'www.{domain}'
    requirements:
        domain: '%domain%'
    defaults:
        domain: '%domain%'
